version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: jcnewsletter
      POSTGRES_PASSWORD: news123
      POSTGRES_DB: jcnewsletter
    ports:
      - "5432:5432"

  newsletter-app:
    build: .
    container_name: newsletter-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jcnewsletter
      SPRING_DATASOURCE_USERNAME: jcnewsletter
      SPRING_DATASOURCE_PASSWORD: news123
    command: ["sh", "-c", "sleep 10 && java -jar /app.jar"]
